require 'rails_helper'
# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/authers', type: :request do
  # Auther. As you add validation to Auther, be sure to
  # adjust the attributes here as well
  let(:valid_attributes) do
    skip('Add a hash of attribute valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Auther.create! valid_attributes
      get authers_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      auther = Auther.create! valid_attributes
      get authers_url(auther)
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      auther = Auther.create! valid_attributes
      get edit_auther_url(auther)
      expect(response).to be_successful
    end 
  end

  describe 'POST /create' do

    context 'with valid parameter' do

      it 'create a new auther' do
        expect do
          post authers_url, params: { auther:valid_attributes }
        end.to change(Auther, :count).by(1)
      end
      it 'redirects to the created auther' do
        post authers_url, params: { auther: valid_attributes }
        expect(response).to redirect_to(authers_url(Auther.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a Auther' do
        expect do
          post authers_url, params: { auther: invalid_attributes }
        end.to change(Auther, :count).by(0)
      end
      it "renders a successful response (i.e. to display the 'new' template)" do
        post authers_url, params: { auther: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'update the requested auther' do
        auther = Auther.create! valid_attributes
        patch authers_url(auther), params: { auther: new_attributes }
        auther.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the auther' do
        auther = Auther.create! valid_attributes
        patch authers_url(auther), params: { auther: new_attributes}
        auther.reload
        expect(response).to redirect_to(authers_url(auther))
      end

    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        auther = Auther.create! valid_attributes
        patch auther_url(auther), params: { auther: invalid_attributes }
        expect(response).to be_successful
      end
    end

  end
  describe 'DELETE /destroy' do

    it 'destroys the requested auther' do
      auther = Auther.create! valid_attributes
      expect do
        delete auther_url(auther)
      end.to change(Auther, :count).by(-1)
    end
    it 'redirects to the authers list' do
      auther = Auther.create! valid_attributes
      delete auther_url(auther)
      expect(response).to redirect_to(auther_url)
    end
  end
end